# pylint: disable=invalid-name
"""create_models

Revision ID: ae2843fc10ff
Revises:
Create Date: 2021-01-19 03:52:23.590839

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae2843fc10ff"
down_revision = None
branch_labels = None
depends_on = None


# pylint: disable=no-member


def upgrade():
    """
    Commands auto generated by Alembic - please adjust!
    """
    op.create_table(
        "student",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teacher",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "homework",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("deadline", sa.Interval(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teacher.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "result",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("solution", sa.String(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("homework_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homework.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    """
    Commands auto generated by Alembic - please adjust!
    """
    op.drop_table("result")
    op.drop_table("homework")
    op.drop_table("teacher")
    op.drop_table("student")
