repos:

- repo: local
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    args: ['--check']
    language: python
    language_version: python3
    require_serial: true
    types: [python]

- repo: local
  hooks:
  - id: isort
    name: isort
    entry: isort
    args: [
      '--profile',
      'black',
      '--check'
    ]
    require_serial: true
    language: python
    types: [python]

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]
    require_serial: true
