repos:

- repo: local
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black --check
    language: python
    language_version: python3
    require_serial: true
    types: [python]

- repo: local
  hooks:
  - id: isort
    name: isort
    entry: isort --profile black --check
    require_serial: true
    language: python
    types: [python]
    args: ['--filter-files']

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]
    require_serial: true
